apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gvisor-dev
resources:
  - deployment.yml
  - service.yml
  - network-policy.yml
configMapGenerator:
  - name: gameworld-searxng-settings
    files:
      - settings.yml
