use_default_settings:
  engines:
    keep_only:
      - google
      - semantic scholar

general:
  instance_name: GameWorld Research Search Pilot
search:
  formats: [html, json]
  default_lang: en
  autocomplete: ""
server:
  limiter: false
  image_proxy: false
outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
engines:
  - name: google
    disabled: false
  - name: semantic scholar
    disabled: false
